# Generated by Django 5.0.4 on 2024-05-01 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='employers',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('locations', models.CharField(max_length=255)),
                ('software', models.BooleanField()),
                ('hardware', models.BooleanField()),
                ('business', models.BooleanField()),
                ('research', models.BooleanField()),
                ('engineering', models.BooleanField()),
                ('sales', models.BooleanField()),
                ('description', models.CharField(max_length=255)),
            ],
        ),
    ]
